Algoritmo "leitura de nomes"

Var
nome: caracter
sobrenome: caracter


Inicio
escreval ("Lista de Nomes")
escreval ("------------------")
escreval ()

escreva ("Digite o nome da pessoa: ")
leia (nome)
escreva ("Digite o sobrenome da pessoa: ")
leia (sobrenome)
escreva ("Digite o nome e o sobrenome da pessoa: ")
escreval (nome+" "+sobrenome)
escreva ("O nome e o sobrenome da pessoa é: ")
escreva (nome," ", sobrenome)


Fimalgoritmo