Algoritmo "EXERCICIO 8"

Var
   nome: caracter
   idade: inteiro
   apos: inteiro
   x: inteiro


Inicio
   Escreva ("Digite o nome do usuário aqui: ")
   leia (nome)
   Escreva ("Digite a idade do usuário aqui: ")
   leia (idade)

   apos
   <- 54

   se (idade<18) entao
      escreva ("Você ainda é muito novo!")
   senao (idade>=18)
   escreva (nome, " , Falta", apos - idade , " anos para você se aposentar!")
   fimse
   
   


   

Fimalgoritmo