Algoritmo "EXERCICIO 8"

Var
p1, p2, p3: real


Inicio
Escreva ("Quantos picolés do tipo 1 foi vendido?: ")
leia (p1)

Escreva ("E quanto de dinheiro foi arrecadado?: ", p1*0.5)

Escreva ("Quantos picolés do tipo 2 foi vendido?: ")
leia (p2)

Escreva ("E quanto de dinheiro foi arrecadado?: ", p2*0.6)

Escreva ("Quantos picolés do tipo 3 foi vendido?: ")
leia (p3)

Escreva ("E quanto de dinheiro foi arrecadado?: ", p3*0.75)


Fimalgoritmo